version: '3.2'

networks:
  farm:

services:
  bdc:
    build:
      context: ./bdc
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - farm
    ports:
      - 9991:9990
    restart: on-failure

  bhc1:
    build:
      context: ./bhc1
    depends_on:
      - bdc
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - farm
    restart: on-failure

  bhc2:
    build:
      context: ./bhc2
    depends_on:
      - bdc
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - farm
    restart: on-failure

  fdc:
    build:
      context: ./fdc
    depends_on:
      - bdc
      - bhc1
      - bhc2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - farm
    ports:
      - 9990:9990
    restart: on-failure

  fhc1:
    build:
      context: ./fhc1
    depends_on:
      - fdc
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - farm
    restart: on-failure

  fhc2:
    build:
      context: ./fhc2
    depends_on:
      - fdc
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - farm
    restart: on-failure

  lb:
    build:
      context: ./lb
    depends_on:
      - fhc1
      - fhc2
      - bhc1
      - bhc2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - farm
    ports:
      - 8080:80
    restart: on-failure
