version: '3.2'

networks:
  cluster:

services:
  master:
    build:
      context: ./master
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - cluster
    ports:
      - 8080:8080
      - 9990:9990
    restart: on-failure

  slave:
    build:
      context: ./slave
    depends_on:
      - master
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - cluster
    ports:
      - 8081:8080
    restart: on-failure
